os:
  - linux

language: php

php:
  - '7.2'

env:
    - ILLUMINATE_VERSION=5.1.* PHPUNIT_VERSION=~4.0
    - ILLUMINATE_VERSION=5.2.* PHPUNIT_VERSION=~4.0
    - ILLUMINATE_VERSION=5.3.* PHPUNIT_VERSION=~5.0
    - ILLUMINATE_VERSION=5.4.* PHPUNIT_VERSION=~5.7
    - ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0
    - ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0
    - ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0
    - ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=^7.5 COVERAGE=true

matrix:
    # For each PHP version we exclude the coverage env, except for PHP 7.1
    exclude:
        # Don't test Laravel 5.5 and up on PHP 5.6
        - php: 5.6
          env: ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0
        - php: 5.6
          env: ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0
        - php: 5.6
          env: ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0
        - php: 5.6
          env: ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=^7.5 COVERAGE=true
        # Test Laravel 5.5 and down on PHP 7.0
        - php: 7.0
          env: ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0
        - php: 7.0
          env: ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0
        - php: 7.0
          env: ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=^7.5 COVERAGE=true
        # Test only Laravel 5.4 and up on PHP 7.1
        - php: 7.1
          env: ILLUMINATE_VERSION=5.1.* PHPUNIT_VERSION=~4.0
        - php: 7.1
          env: ILLUMINATE_VERSION=5.2.* PHPUNIT_VERSION=~4.0
        - php: 7.1
          env: ILLUMINATE_VERSION=5.3.* PHPUNIT_VERSION=~5.0



before_script:

  - composer self-update
  - composer require php-coveralls/php-coveralls
  - composer install
  - composer install --dev
  - mkdir -p build/logs
  - cp .env.travis .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - npm install -g grunt-cli
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install -g grunt-cli
  - npm install -g jshint
  - npm install

script:

  - phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpunit --coverage-html -v
  - jshint resources/assets/js/modules/*


after script:
  - php vendor/bin/coveralls -v
  - php vendor/bin/php-coveralls -v
  - travis_retry php vendor/bin/php-coveralls -v
  
