os:
  - linux

language: php

php:
  - '7.2'

before_script:

  - composer self-update
  - composer install
  - composer install --dev
  - cp .env.travis .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - npm install -g grunt-cli
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install -g grunt-cli
  - npm install -g jshint
  - npm install

script:
  - php vendor/bin/coveralls -v
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/assets/js/modules/*
