codecov:
  token:  44478cf8-e308-4f33-b8c4-8783cd5aebc3
  bot: "codecov-io"
  ci:
    - "travis-ci.com"
  strict_yaml_branch: "yaml-config"
  max_report_age: 10000000000000000
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1
    wait_for_ci: yes
